"""Create stock model

Revision ID: bf590c8b3af0
Revises: 
Create Date: 2023-10-25 03:07:50.687773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf590c8b3af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open_price', sa.String(), nullable=True),
    sa.Column('higher_price', sa.String(), nullable=True),
    sa.Column('lower_price', sa.String(), nullable=True),
    sa.Column('variation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
